DROP TABLE IF EXISTS users, items, bookings, comments, item_requests;

CREATE TABLE IF NOT EXISTS users (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE,
                                     name VARCHAR(255) NOT NULL,
                                     email VARCHAR(512) NOT NULL UNIQUE,
                                     CONSTRAINT pk_user PRIMARY KEY (id),
                                     CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS item_requests (
                                             id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE,
                                             description VARCHAR(255) NOT NULL,
                                             created TIMESTAMP WITH TIME ZONE NOT NULL,
                                             author_id BIGINT NOT NULL,
                                             CONSTRAINT pk_item_requests PRIMARY KEY (id),
                                             FOREIGN KEY (author_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS items (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE,
                                     user_id BIGINT NOT NULL,
                                     name VARCHAR(255) NOT NULL,
                                     description VARCHAR(512) NOT NULL,
                                     is_available BOOLEAN NOT NULL,
                                     request_id BIGINT,
                                     CONSTRAINT pk_item PRIMARY KEY (id),
                                     FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
                                     FOREIGN KEY (request_id) REFERENCES item_requests (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS bookings (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE,
                                     start_date TIMESTAMP WITH TIME ZONE NOT NULL,
                                     end_date TIMESTAMP WITH TIME ZONE NOT NULL,
                                     status VARCHAR(55) DEFAULT 'WAITING',
                                     booker_id BIGINT NOT NULL,
                                     item_id BIGINT NOT NULL,
                                     CONSTRAINT pk_booking PRIMARY KEY (id),
                                     FOREIGN KEY (booker_id) REFERENCES users (id) ON DELETE CASCADE,
                                     FOREIGN KEY (item_id) REFERENCES items (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS comments (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE,
                                     text VARCHAR(255) NOT NULL,
                                     author_id BIGINT NOT NULL,
                                     item_id BIGINT NOT NULL,
                                     created TIMESTAMP WITH TIME ZONE NOT NULL,
                                     CONSTRAINT pk_comment PRIMARY KEY (id),
                                     FOREIGN KEY (author_id) REFERENCES users (id) ON DELETE CASCADE,
                                     FOREIGN KEY (item_id) REFERENCES items (id) ON DELETE CASCADE
);